# Generated by Django 5.0 on 2023-12-12 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(verbose_name='ID Telegram чата для рассылки')),
                ('time', models.TimeField(default=datetime.datetime(2023, 12, 12, 14, 3, 28, 732664), verbose_name='Время рассылки')),
                ('last_date_check', models.DateField(default=datetime.date(2023, 12, 12), verbose_name='Последняя дата рассылки в чат')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
